server:
  servlet:
    context-path: /pick-up-drop-off

spring:
  application:
    name: pick-up-drop-off
  datasource:
    username: admin
    password: admin
    url: 'jdbc:h2:mem:pick-up-drop-off'
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
  profiles:
    active: local