INSERT INTO TB_ADDRESS (DS_STREET, NR_NUMBER, DS_NEIGHBORHOOD, POSTAL_CODE, TP_STATE, TP_COUNTRY)
VALUES ('Rua das Flores', 123, 'Centro', '12345-678', 'SP', 'BR');
INSERT INTO TB_ADDRESS (DS_STREET, NR_NUMBER, DS_NEIGHBORHOOD, POSTAL_CODE, TP_STATE, TP_COUNTRY)
VALUES ('Rua Teste', 9999, 'Distrito Industrial', '12345-678', 'RJ', 'BR');
